apiVersion: v1
kind: Service
metadata:
  name: simpleserver
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
---
# Because this service has no selector, the corresponding Endpoints
# object will not be created. You can manually map the service to
# your own specific endpoints:
kind: Endpoints
apiVersion: v1
metadata:
  name: simpleserver
subsets:
  - addresses:
      - ip: "10.128.0.2"
    ports:
      - port: 8000
