apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data1
  labels:
    app: alertmanager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: meetup-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data2
  labels:
    app: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: meetup-disk-2
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels: 
      app: prometheus
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data2
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: alertmanager
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

