apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
    name: kuard
    internalVersion: 0.0.3
  name: kuardnew
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuardnew
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
