apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx:1.7.9
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  initContainers:
  - name: git-code-downlaod
    image: alpine/git
    command: ['sh', '-c', 'git clone https://github.com/wlsf82/helloworld.git; mv * /cache ']
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
