apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx:1.7.9
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  initContainers:
  - name: template-changer
    image: alpine/git
    command: ['sh', '-c', 'cp /conf/*  /cache; chmod +x /cache/*']
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    - mountPath: /conf
      name: conf
    
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: conf
    configMap:
     name: mysql-conn
