apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-0
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cassandra-disk
    fsType: ext4
