apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuard-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kuard
        version: 1.0.0
    spec:
      containers:
      - name: kuard
        image:  gcr.io/kuar-demo/kuard-amd64:2
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

