apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistnetDisk:
    pdName: meetup-disk
    fsType: ext4

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
