apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kuard
  annotations:
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
  name: kuard
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    internalVersion: 0.0.1
    run: kuard
  type: LoadBalancer
status:
  loadBalancer: {}
