apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
        version: "1.0.0"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:2
        imagePullPolicy: IfNotPresent
        name: kuard
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always