apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuard
    version: 1.0.0
  name: kuard-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9999
  selector:
    app: kuard
    version: 1.0.0
  type: NodePort
status:
  loadBalancer: {}
