apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
  volumeName: pvc-13619eda-d690-11e8-89dc-42010a9c0015 
