apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
    name: kuard
    internalVersion: 0.0.1
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    volumeMounts:
      - name: tls-certs
        mountPath: /tls
        readOnly: true

  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls 
