apiVersion: v1
kind: Pod
metadata:
  labels:
    app: guestbook
    tier: frontend
  name: frontend-pamir
spec:
  containers:
  - env:
    - name: GET_HOSTS_FROM
      value: dns
    image: gcr.io/google_samples/gb-frontend:v3
    imagePullPolicy: IfNotPresent
    name: php-redis
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
