apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    appVersion: 2.0.0
    env: staging
  name: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      appVersion: 1.0.1
      env: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        appVersion: 1.0.1
        env: prod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
        resources: {}
status: {}
