apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
    name: kuard
    internalVersion: 0.0.1
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuard
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      timeoutSeconds: 1
      periodSeconds: 10
      initialDelaySeconds: 30
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure